
USE clubdb; 

LOAD DATA INFILE "persons.csv"
INTO TABLE person
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "dept.csv"
INTO TABLE department
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE "student.csv"
INTO TABLE student
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; 

LOAD DATA INFILE "faculty.csv"
INTO TABLE faculty
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; 

LOAD DATA INFILE "club.csv"
INTO TABLE club
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; 

LOAD DATA INFILE "member_of.csv"
INTO TABLE member_of
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; 

LOAD DATA INFILE "board_of.csv"
INTO TABLE board_of
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; 

LOAD DATA INFILE "supervises.csv"
INTO TABLE supervises
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; 


